### PR TITLE
Add content for accessibility page

### PR DESCRIPTION
**Pull request by Wolfr**

### CODE REVIEW

**Comment by jakobrosenberg** [comment]
"By default, Routify removes the focus on route change. If you want to opt out of this behavior..."

I don't think this is correct. Couldn't find anything in the code and routify.dev doesn't reset focus either.

**Comment by Wolfr** [comment]
I don't get it, it does?

**Comment by jakobrosenberg** [comment]
What do you get if you open your terminal and type ``document.activeElement`` after you navigate?

**Comment by Wolfr** [comment]
I'm just going to let this one sit here for a while until I get to fixing it.

**Comment by Wolfr** [comment]
I am going to close this one, and open a new issue to start on this again when I find the time. This PR is stale.

**Pull request closed without merging**
