### PR TITLE
Update TabsTransition documentation

### PR DESCRIPTION
**Pull request by kierangilliam**

### CODE REVIEW

**Comment by Wolfr** [comment]
Wait, it would be more useful to check against master I think, because this diff is highly unreadable. We don't use the staging branch at the moment.

**Comment by kierangilliam** [comment]
@Wolfr Sorry that is my bad, I severely misunderstood the contributing 'branch logic' guidelines. I will close this PR.

**Comment by Wolfr** [comment]
No no, actually, you did the right thing. CONTRIBUTING.md file  indeed mentions to PR against staging. But I think we should just bring staging up to date with master so I can see the diff properly. Sorry for the confusion.

**Comment by Wolfr** [comment]
I just tried to bring staging up to date, but I don't think we use it enough to be the one to branch off from. Please branch out from master should be the correct guideline. I will fix it.

**Comment by Wolfr** [comment]
@jakobrosenberg hard to see what's going on here, but do you agree with this commit as an improvement?

https://github.com/sveltech/routify-site-2020/pull/158/commits/b01dbd54b677d238ea1270c66f4933037059f08b

**Comment by jakobrosenberg** [comment]
That looks correct, but the merge should probably be against the master at this state. Or we should get the staging branch up to date.

**Comment by kierangilliam** [comment]
Sorry about the confusion again - new to contributing! I created a separate pull request and am closing this one.

**Pull request closed without merging**
