### PR TITLE
bug fix: missing '$' in front of $metatags

### PR DESCRIPTION
**Pull request by jkdoshi**

### CODE REVIEW

**Comment by Wolfr** [comment]
Thank you!

**Comment by jakobrosenberg** [comment]
I merged this by mistake. There's not supposed to be $ in front of metatags. They're not stores. >.<

**Comment by Wolfr** [comment]
Hm OK I thought this was an actual fix, sorry!

**Comment by jakobrosenberg** [comment]
Me too. I only realized because I had a support issue about the metatags on Discord yesterday or the day before about the metatags documentation being wrong. 😋

**Comment by jkdoshi** [comment]
Sorry, my bad. I didn't know that they are not stores.

**Comment by jakobrosenberg** [comment]
No worries, @jkdoshi . I'd forgotten too. I only remembered cause I was asked about it on Discord a few days ago.

**Pull request merged**
